/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jundy.client;
@SuppressWarnings("all")
/** Category that the client is allows to transact on */
@org.apache.avro.specific.AvroGenerated
public enum Channel {
  INTERNET, IVR, PHONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Channel\",\"namespace\":\"com.jundy.client\",\"doc\":\"Category that the client is allows to transact on\",\"symbols\":[\"INTERNET\",\"IVR\",\"PHONE\"],\"default\":\"INTERNET\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
